apiVersion: v1
kind: Pod
metadata:
  name: reddit-analysis
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 260433
#    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: trust-ucd
      image: twford/fais_lab  # image name
      imagePullPolicy: Always
      resources:
        requests:
          memory: "32Gi"
          cpu: "16"
          nvidia.com/gpu: '1'
        limits:
          memory: "32Gi"
          cpu: "16"
          nvidia.com/gpu: '1'
      volumeMounts:
      - name: code
        mountPath: "/app/"
#      command: [""]
      stdin: true
      tty: true
  imagePullSecrets:
    - name: ghcr-secret
  volumes:
  - name: code
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/twford/repos/reddit
