apiVersion: v1
kind: Pod
metadata:
  name: reddit-analysis
  labels:
    app: reddit-analysis
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 260433
    runAsGroup: 50038
  containers:
    - name: trust-ucd
      image: ghcr.io/tford9/trustucd:master  # image name
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "32Gi"
          cpu: "16"
          nvidia.com/gpu: '1'
        limits:
          memory: "32Gi"
          cpu: "16"
          nvidia.com/gpu: '1'
      volumeMounts:
        - name: home
          mountPath: "/app"
      stdin: true
      tty: true
  imagePullSecrets:
    - name: ghcr-secret
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/twford/repos/reddit
